"use client";
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {applicantStatus} from '@/lib/service-status';
import {fetchJsonWithTimeout} from '@/lib/client-request';
type Status={status:string;createdAt:string;submittedAt:string|null;reviewedAt:string|null;server:{name:string;slug:string}|null;notifications:boolean};
export default function ApplicantStatus({sessionId}:{sessionId:string}) {
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetchJsonWithTimeout<Status&{error?:string}>(`/api/applicant/status/${sessionId}`,{cache:'no-store'},15000,'Status timed out. Please refresh.');if(!r.ok||!r.data)throw new Error(r.data?.error||'Status unavailable.');setData(r.data);setError('');}catch(e){setError(e instanceof Error?e.message:'Status unavailable.');}},[sessionId]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},30000);return()=>clearInterval(timer);},[load]);
 const status=applicantStatus(data?.status||'');
 return <main className="portal-wrap"><section className="status-page panel"><Link className="brand" href="/"><span className="brand-mark"/>Dexlyy</Link><span className="eyebrow">Private application status</span><h1>{data?status.title:'Your application'}</h1>{data?<><p>{data.server?.name} · {status.detail}</p><ol className="status-steps">{['Application started','Interview submitted','Team decision'].map((s,i)=><li key={s} className={status.step>i?'complete':''}>{s}</li>)}</ol><p className="subtle">Started {new Date(data.createdAt).toLocaleDateString()}{data.submittedAt?` · Submitted ${new Date(data.submittedAt).toLocaleDateString()}`:''}</p>{data.status==='interviewing'&&<Link className="btn btn-primary" href={`/interview/${sessionId}`}>Continue interview</Link>}<label className="service-checkbox"><input type="checkbox" checked={data.notifications} disabled={busy} onChange={async e=>{const enabled=e.target.checked;setBusy(true);try{const r=await fetchJsonWithTimeout(`/api/applicant/status/${sessionId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})},15000,'Could not save preference.');if(!r.ok)throw new Error('Could not save preference.');setData({...data,notifications:enabled});}catch(e){setError(e instanceof Error?e.message:'Could not save preference.');}finally{setBusy(false);}}}/> Send future status updates to my Discord DMs</label><p className="subtle">Optional. Discord may block messages depending on your privacy settings. This page remains the source of truth.</p></>:!error?<p>Loading your status…</p>:<Link className="btn btn-primary" href={`/login?next=${encodeURIComponent(`/application-status/${sessionId}`)}`}>Sign in to view your application</Link>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn btn-ghost" onClick={()=>void load()}>Refresh status</button></section></main>;
}
