"use client";
import {useCallback,useEffect,useState} from 'react';
import {fetchJsonWithTimeout} from '@/lib/client-request';
type Work={assignee:string;members:Array<{user_id:string;name:string}>;notes:Array<{id:string;body:string;author:string;created_at:string}>};
export default function ReviewCollaboration({applicationId}:{applicationId:string}) {
 const [data,setData]=useState<Work|null>(null),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetchJsonWithTimeout<Work>(`/api/applications/${applicationId}/work`,{cache:'no-store'},15000,'Team workspace timed out.');if(!r.ok||!r.data)throw new Error('Team workspace unavailable.');setData(r.data);setError('');}catch(e){setError(e instanceof Error?e.message:'Team workspace unavailable.');}},[applicationId]);
 useEffect(()=>{void load();},[load]);
 async function save(body:object){setBusy(true);setError('');try{const r=await fetchJsonWithTimeout(`/api/applications/${applicationId}/work`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},15000,'Save timed out. Refresh before retrying.');if(!r.ok)throw new Error('Update could not be saved. Refresh and try again.');if('note' in body)setNote('');await load();}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 return <section className="panel service-panel"><div className="panel-title"><div><span className="eyebrow">Private team workspace</span><h2>Review together</h2></div><button className="btn btn-ghost btn-small" onClick={()=>void load()}>Refresh</button></div><p className="subtle">Only this community’s review team can see notes and assignments. Assignments coordinate work; every authorised reviewer can still make a decision.</p>{data&&<><label className="label">Assigned reviewer<select className="select" value={data.assignee} disabled={busy} onChange={e=>void save({assignee:e.target.value||null})}><option value="">Unassigned</option>{data.assignee&&!data.members.some(m=>m.user_id===data.assignee)&&<option value={data.assignee}>Former team member — reassign</option>}{data.members.map(m=><option value={m.user_id} key={m.user_id}>{m.name}</option>)}</select></label><form className="form-stack" onSubmit={e=>{e.preventDefault();void save({note});}}><label className="label">Private note<textarea className="textarea" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add context for the next reviewer. Avoid unnecessary personal information." required/></label><button className="btn btn-primary" disabled={busy||!note.trim()}>{busy?'Saving…':'Add team note'}</button></form><div className="team-notes" aria-label="Recent team notes">{data.notes.length?data.notes.map(n=><article key={n.id}><header><strong>{n.author}</strong><time>{new Date(n.created_at).toLocaleString()}</time></header><p>{n.body}</p></article>):<p className="subtle">No team notes yet.</p>}</div><small className="subtle">Showing the latest 50 notes.</small></>}{error&&<p role="alert" className="form-error">{error}</p>}</section>;
}
