"use client";
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {CheckCircle2,RefreshCw} from 'lucide-react';
import {fetchJsonWithTimeout} from '@/lib/client-request';
type Insights={setup:{discord:boolean;role:boolean;questions:number;fields:number;active:boolean;webhook:boolean;ai:boolean};metrics:{applications:number;submitted:number;unfinished:number;notStarted:number;interviewIncomplete:number;stale:number;waiting:number;overdue:number;reviewHours:number|null};billing:{plan_key:string;status:string;monthly_interview_limit:number;monthly_interviews_used:number;monthly_period_end:string;subscription_period_end:string}|null;reminders:boolean;canConfigure:boolean;verifiedAt:string|null};
export default function ServiceInsights({serverId,slug}:{serverId:string;slug:string}) {
 const [data,setData]=useState<Insights|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[check,setCheck]=useState('');
 const load=useCallback(async()=>{try{const r=await fetchJsonWithTimeout<Insights>(`/api/servers/${serverId}/service`,{cache:'no-store'},15000,'Insights timed out.');if(!r.ok||!r.data)throw new Error('Service insights are temporarily unavailable.');setData(r.data);setError('');}catch(e){setError(e instanceof Error?e.message:'Insights unavailable.');}},[serverId]);
 useEffect(()=>{void load();},[load]);
 async function action(action:string,enabled?:boolean){setBusy(true);setError('');try{const r=await fetchJsonWithTimeout<{error?:string;message?:string}>(`/api/servers/${serverId}/service`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,enabled})},15000,'Check timed out.');if(!r.ok)throw new Error(r.data?.error||'Please retry.');if(action==='check')setCheck(r.data?.message||'Check finished.');else await load();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
 if(!data)return <section className="panel service-panel"><p>{error||'Checking setup and usage…'}</p><button className="btn" onClick={()=>void load()}>Retry</button></section>;
 const steps=[{label:'Connect Discord',done:data.setup.discord},{label:'Choose an approval role',done:data.setup.role},{label:'Prepare your application',done:data.setup.fields>0},{label:'Set interview questions',done:data.setup.questions>0}];
 const billingReady=data.billing?.status==='active'||(data.billing?.status==='suspended'&&data.billing.subscription_period_end>new Date().toISOString().slice(0,10));
 const ready=steps.every(s=>s.done)&&data.setup.active&&data.setup.ai&&billingReady;
 const used=data.billing&&data.billing.monthly_period_end<=new Date().toISOString().slice(0,10)?0:data.billing?.monthly_interviews_used||0;
 return <section className="panel service-panel"><div className="panel-title"><div><span className="eyebrow">Setup & service health</span><h2>{ready?'Your portal essentials are ready':'Let’s get your portal ready'}</h2></div><button className="btn btn-ghost btn-small" onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button></div><ol className="setup-checklist">{steps.map((step,i)=><li key={step.label} className={step.done?'complete':''}><span>{step.done?<CheckCircle2 size={18}/>:i+1}</span><div><strong>{step.label}</strong><small>{step.done?'Configured':'Needs attention'}</small></div>{data.canConfigure&&<Link href={`/dashboard/servers/${serverId}/settings`}>{step.done?'Edit':'Set up'}</Link>}</li>)}</ol><div className="service-actions"><Link className="btn btn-ghost" href={`/portal/${slug}`} target="_blank" rel="noreferrer">Preview applicant journey</Link>{data.canConfigure&&<button className="btn btn-primary" disabled={busy} onClick={()=>void action('check')}>{busy?'Checking…':'Test Discord connection'}</button>}</div><p className="subtle">Preview the portal, check your microphone, and complete a test interview before sharing your player link. A submitted test interview uses one credit.</p>{check&&<p role="status" className="service-message">{check}</p>}{!data.setup.ai&&<p className="form-error">Voice service is not configured. Contact Dexlyy support.</p>}{!data.setup.active&&<p className="form-error">This portal is disabled. Review portal settings before sharing it.</p>}
 <div className="service-usage"><strong>{data.billing?.plan_key||'No plan'} · {data.billing?.status||'inactive'}</strong><span>{data.billing?data.billing.monthly_interview_limit<0?'Unlimited monthly interviews':`${Math.max(0,data.billing.monthly_interview_limit-used)} interviews remaining this month`:'Activate a plan to accept interviews'}</span><small>{data.billing?.plan_key==='free'?'Monthly allowance':`Next billing date: ${data.billing?.subscription_period_end||'not set'}`}</small></div>
 <details className="service-details"><summary>Application insights · last 30 days</summary><div className="service-metrics">{[['Applications opened',data.metrics.applications],['Submitted',data.metrics.submitted],['Interview not started',data.metrics.notStarted],['Interview unfinished',data.metrics.interviewIncomplete],['Unfinished after 24h',data.metrics.stale],['Awaiting review',data.metrics.waiting],['Waiting over 48h',data.metrics.overdue],['Average review time',data.metrics.reviewHours===null?'—':`${data.metrics.reviewHours}h`],['Submission rate',data.metrics.applications?`${Math.round(data.metrics.submitted/data.metrics.applications*100)}%`:'—']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="subtle">Based on applications started in the last 30 days and still retained. Unfinished applications may still be completed; they are not confirmed abandonments. Review time starts at interview submission.</p></details>
 {data.canConfigure&&<label className="service-checkbox"><input type="checkbox" checked={data.reminders} disabled={busy||!data.setup.webhook} onChange={e=>void action('reminders',e.target.checked)}/>Daily Discord reminder when applications wait more than 48 hours</label>}{data.canConfigure&&!data.setup.webhook&&<p className="subtle">Configure your private staff webhook in settings to enable reminders.</p>}{error&&<p role="alert" className="form-error">{error}</p>}</section>;
}
