import Link from 'next/link';
import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Partner Programme Terms', alternates: { canonical: '/partners/terms' } };
export default function PartnerTerms() {
  return <main className="affiliate-page"><article className="affiliate-container affiliate-terms"><Link href="/partners" className="affiliate-back">← Partner programme</Link><span className="eyebrow">VERSION 2026-09-02</span><h1>Clear terms.<br />A fair partnership.</h1><p>These rules describe the Dexlyy approved-partner pilot. Participation is free, subject to approval and payout eligibility. No income is guaranteed.</p>
    <h2>1. What earns commission</h2><p>Approved partners earn 15% of qualifying live USD product payments actually collected from attributed new customers, after discounts and excluding taxes. Dexlyy absorbs normal customer payment-processing fees. Monthly and annual subscriptions and extra interview packs qualify. Annual commission is earned once on the annual payment, not twelve times. Trials, free grants, sandbox transactions and unpaid invoices do not qualify.</p>
    <h2>2. Attribution</h2><p>The last accepted valid referral before a new account signs up is eligible for a 30-day signup window. Once assigned, one partner remains attached to that customer for qualifying renewals, plan changes and resubscriptions. Existing accounts created before this programme launched are excluded. New accounts may enter a code within 30 days of signup, before their first purchase. Attribution cannot be reassigned after acceptance. Missing or blocked browser storage and switching devices can prevent automatic tracking; a code can be entered before purchase instead.</p>
    <h2>3. Clearance and payouts</h2><p>Commissions remain pending for at least 30 days after payment verification. Eligible balances of $25 or more are reviewed monthly; smaller balances roll forward. Payout availability depends on country, identity and payment-provider requirements. Payout currency is USD; your provider may apply recipient conversion or withdrawal charges. Updating a payout address requires re-verification and a 48-hour security hold. Never share your PayPal password or banking password with us.</p>
    <h2>4. Refunds and disputes</h2><p>Refunds and reversals reduce the original commission proportionally, including after payout. Adjustments may offset future earnings and create a negative available balance. A holding period does not eliminate later disputes. No commission is earned merely because a customer uses an interview or because a subscription is activated without payment.</p>
    <h2>5. Responsible promotion</h2><p>Clearly disclose that you earn commission near your recommendation and link, including in relevant videos. Do not self-refer, create duplicate customer accounts, spam, impersonate Dexlyy, make guaranteed-income claims, or misrepresent prices or features. This is a single-level programme: there are no rewards for recruiting partners. Use only approved promotional material and truthful statements.</p>
    <h2>6. Review and suspension</h2><p>Dexlyy may pause links and payouts while reviewing suspected abuse, disputed payments, identity, or payout eligibility. Suspended partners do not earn new commissions while suspended. Financial records remain available. Contact support to dispute an attribution or accounting error. Programme changes will be communicated; historical recorded commissions retain their original calculation, subject to refunds and fraud review.</p>
    <h2>7. Privacy</h2><p>With your permission we store a first-party, HTTP-only referral cookie for up to 30 days. You can decline without losing access to Dexlyy or clear it in your browser settings. On signup, accepted attribution is saved to the customer account for recurring-payment accounting. Partners see their own financial totals and anonymised commission entries, not customer emails, recordings or interview transcripts. Authorised Dexlyy administrators can review applications, payout details and financial audit records. Financial records are retained for accounting, disputes and applicable retention obligations; expired unclaimed referral tokens are deleted during maintenance.</p>
    <h2>8. Eligibility and questions</h2><p>Applicants must be legally able to enter this arrangement and receive payouts in their country, and are responsible for applicable tax reporting. Approval is not automatic. Contact <a href="mailto:support@dexlyy.com">support@dexlyy.com</a> for eligibility, privacy, account closure, outstanding balances, or dispute enquiries.</p><Link href="/partners" className="btn btn-primary">Back to partners</Link></article></main>;
}
