-- Security hardening: keep privileged and identity-bearing writes behind the
-- application API, minimize anonymous reads, and enforce abuse limits in the
-- database so they work across multiple application instances.

-- Public portal data is now returned as a minimal DTO by /api/portal/[slug].
-- Do not expose Discord role IDs, owner IDs, or staff configuration through
-- Supabase's anonymous Data API.
drop policy if exists "active subscribed portals are public" on public.servers;
revoke select on public.servers from anon;

drop policy if exists "active application fields are public" on public.application_fields;
revoke select on public.application_fields from anon;

-- Applicants must not be able to enumerate the configured interview prompts
-- and private scenario guidance before an interview begins.
drop policy if exists "active interview questions are available" on public.question_bank;

-- Identity-bearing application creation and review decisions are performed by
-- authenticated server routes after Discord and resource authorization checks.
drop policy if exists "authenticated users submit applications" on public.applications;
drop policy if exists "managers review applications" on public.applications;
revoke insert, update on public.applications from authenticated;

-- Session creation, recording linkage, and resets are also mediated by server
-- routes. Applicants retain read access and scoped Storage upload access.
drop policy if exists "participants create interviews" on public.interview_sessions;
drop policy if exists "participants update interviews" on public.interview_sessions;
revoke insert, update on public.interview_sessions from authenticated;

-- Staff membership changes use the service-only invite functions. Prevent an
-- owner from mutating a membership row's server/user identity directly.
drop policy if exists "owners manage membership" on public.server_members;
revoke update on public.server_members from authenticated;

drop policy if exists "owners remove membership" on public.server_members;
create policy "owners remove non-owner membership"
  on public.server_members for delete
  to authenticated
  using (
    role <> 'owner'
    and exists (
      select 1 from public.servers s
      where s.id = server_members.server_id
        and s.owner_id = (select auth.uid())
    )
  );

-- Audit events are generated by the trusted server routes, not browsers.
drop policy if exists "managers write audit logs" on public.audit_logs;
revoke insert on public.audit_logs from authenticated;

-- Prevent unexpectedly large or executable uploads. Recordings remain private.
update storage.buckets
set public = false,
    file_size_limit = 52428800,
    allowed_mime_types = array['audio/webm', 'audio/mp4', 'audio/ogg']::text[]
where id = 'interview-recordings';

-- Distributed fixed-window rate limiting for expensive and brute-forceable
-- endpoints. The raw identifiers are hashed by the application before storage.
create table if not exists private.api_rate_limits (
  key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now()
);

revoke all on private.api_rate_limits from public, anon, authenticated;

create or replace function public.consume_api_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if p_key is null or char_length(p_key) <> 64
     or p_limit < 1 or p_limit > 10000
     or p_window_seconds < 1 or p_window_seconds > 86400 then
    raise exception 'Invalid rate-limit parameters.' using errcode = 'P0001';
  end if;

  insert into private.api_rate_limits as limits(key, window_started_at, request_count, updated_at)
  values (p_key, now(), 1, now())
  on conflict (key) do update
  set window_started_at = case
        when limits.window_started_at <= now() - make_interval(secs => p_window_seconds) then now()
        else limits.window_started_at
      end,
      request_count = case
        when limits.window_started_at <= now() - make_interval(secs => p_window_seconds) then 1
        else limits.request_count + 1
      end,
      updated_at = now()
  returning request_count into v_count;

  return v_count <= p_limit;
end;
$$;

revoke all on function public.consume_api_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_api_rate_limit(text, integer, integer) to service_role;

-- Track signed PayPal events so retries are idempotent and older events cannot
-- overwrite newer subscription state.
alter table public.owner_billing
  add column if not exists paypal_last_event_at timestamptz;

create table if not exists public.paypal_webhook_events (
  event_id text primary key,
  event_type text not null,
  occurred_at timestamptz,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.paypal_webhook_events enable row level security;
revoke all on public.paypal_webhook_events from public, anon, authenticated;

-- Keep the RPC callable by the signed-in applicant for atomic credit charging,
-- but reject oversized, malformed, or out-of-sequence transcript submissions
-- even when somebody bypasses the Next.js route and calls Supabase directly.
create or replace function public.submit_interview(p_session_id uuid, p_transcript jsonb default '[]'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session record;
  v_billing record;
  v_credit_source text;
  v_remaining integer;
begin
  if (select auth.uid()) is null then
    raise exception 'You must be signed in.' using errcode = 'P0001';
  end if;
  if jsonb_typeof(p_transcript) <> 'array'
     or jsonb_array_length(p_transcript) > 200
     or pg_column_size(p_transcript) > 131072
     or exists (
       select 1 from jsonb_array_elements(p_transcript) item
       where jsonb_typeof(item) <> 'object'
          or item->>'role' not in ('user', 'assistant')
          or item->>'text' is null
          or char_length(item->>'text') > 4000
     ) then
    raise exception 'The interview transcript is invalid or too large.' using errcode = 'P0001';
  end if;

  select i.id, i.status, i.application_id, a.applicant_user_id, s.owner_id
    into v_session
    from public.interview_sessions i
    join public.applications a on a.id = i.application_id
    join public.servers s on s.id = i.server_id
   where i.id = p_session_id
   for update of i;

  if not found or v_session.applicant_user_id <> (select auth.uid()) then
    raise exception 'Interview session not found.' using errcode = 'P0001';
  end if;
  if v_session.status = 'completed' then
    return jsonb_build_object('ok', true, 'already_submitted', true);
  end if;
  if v_session.status not in ('created', 'in_progress') then
    raise exception 'This interview cannot be submitted.' using errcode = 'P0001';
  end if;

  select * into v_billing
    from public.owner_billing
   where user_id = v_session.owner_id
   for update;

  if not found or not (
    v_billing.status = 'active'
    or (v_billing.status = 'suspended' and current_date < v_billing.monthly_period_end)
  ) then
    raise exception 'The server subscription is not active.' using errcode = 'P0001';
  end if;

  if current_date >= v_billing.monthly_period_end then
    update public.owner_billing
       set monthly_interviews_used = 0,
           monthly_period_start = monthly_period_end,
           monthly_period_end = (monthly_period_end + interval '1 month')::date
     where id = v_billing.id
    returning * into v_billing;
  end if;

  if v_billing.monthly_interview_limit = -1 then
    v_credit_source := 'monthly'; v_remaining := -1;
  elsif v_billing.monthly_interviews_used < v_billing.monthly_interview_limit then
    update public.owner_billing
       set monthly_interviews_used = monthly_interviews_used + 1
     where id = v_billing.id
    returning monthly_interviews_used into v_billing.monthly_interviews_used;
    v_credit_source := 'monthly';
    v_remaining := v_billing.monthly_interview_limit - v_billing.monthly_interviews_used;
  elsif v_billing.prepaid_interviews > 0 then
    update public.owner_billing
       set prepaid_interviews = prepaid_interviews - 1
     where id = v_billing.id
    returning prepaid_interviews into v_billing.prepaid_interviews;
    v_credit_source := 'prepaid'; v_remaining := v_billing.prepaid_interviews;
  else
    raise exception 'No interview credits remaining.' using errcode = 'P0001';
  end if;

  update public.interview_sessions
     set status = 'completed', completed_at = coalesce(completed_at, now()), transcript = p_transcript
   where id = p_session_id;
  update public.applications set status = 'under_review' where id = v_session.application_id;

  return jsonb_build_object('ok', true, 'credit_source', v_credit_source, 'remaining', v_remaining);
end;
$$;

revoke all on function public.submit_interview(uuid, jsonb) from public;
revoke execute on function public.submit_interview(uuid, jsonb) from anon;
grant execute on function public.submit_interview(uuid, jsonb) to authenticated;
